/*
 * GPWBPP PixInsight launcher
 *
 * Clean-room boundary:
 * - This file is an independent launcher for the external open GPWBPP CLI.
 * - It does not implement PixInsight processing algorithms.
 * - It does not read, import, or modify any official preprocessing scripts.
 * - It does not write to the input image directory.
 */

#feature-id Utilities > GPWBPP
#feature-info Clean-room launcher for the external GPWBPP command-line pipeline.

#include <pjsr/Sizer.jsh>
#include <pjsr/FrameStyle.jsh>
#include <pjsr/TextAlign.jsh>

function quoteArg(value) {
   var text = String(value);
   if (text.length == 0)
      return "\"\"";
   if (text.search(/[ \t"]/g) < 0)
      return text;
   return "\"" + text.replace(/"/g, "\\\"") + "\"";
}

function buildAuditArgs(settings) {
   var args = [
      "audit",
      "--root", settings.root,
      "--out", settings.out,
      "--backend", settings.backend,
      "--memory-mode", settings.memoryMode,
      "--local-normalization", settings.localNormalization,
      "--integration-weighting", settings.integrationWeighting,
      "--integration-rejection", settings.integrationRejection
   ];
   if (settings.memoryMode == "resident") {
      args.push("--resident-registration");
      args.push(settings.residentRegistration);
      args.push("--resident-warp-interpolation");
      args.push(settings.residentWarpInterpolation);
   }
   return args;
}

function commandLine(settings) {
   var parts = [quoteArg(settings.executable)];
   var args = buildAuditArgs(settings);
   for (var i = 0; i < args.length; ++i)
      parts.push(quoteArg(args[i]));
   return parts.join(" ");
}

function writeCommandFile(settings) {
   var path = File.saveFileDialog("Write GPWBPP command file", ".cmd", "Command files (*.cmd)");
   if (path == "")
      return;
   var file = new File();
   file.createForWriting(path);
   file.outTextLn("@echo off");
   file.outTextLn("rem Generated by the clean-room GPWBPP PixInsight launcher.");
   file.outTextLn("rem Review paths before running. Source image directories are read-only inputs.");
   file.outTextLn(commandLine(settings));
   file.close();
   Console.writeln("Wrote command file: " + path);
}

function runExternal(settings) {
   var process = new ExternalProcess();
   var args = buildAuditArgs(settings);
   Console.writeln("Starting GPWBPP:");
   Console.writeln(commandLine(settings));
   process.start(settings.executable, args);
   while (process.isRunning)
      process.waitForFinished(250);
   if (process.exitCode != 0)
      throw new Error("GPWBPP exited with code " + process.exitCode);
   Console.writeln("GPWBPP finished successfully.");
}

function makeLabel(parent, text) {
   var label = new Label(parent);
   label.text = text;
   label.textAlignment = TextAlign_Right | TextAlign_VertCenter;
   return label;
}

function makeEdit(parent, text) {
   var edit = new Edit(parent);
   edit.text = text;
   edit.minWidth = 520;
   return edit;
}

function GPWBPPDialog() {
   this.__base__ = Dialog;
   this.__base__();

   this.windowTitle = "GPWBPP";

   var executable = makeEdit(this, "gpwbpp");
   var root = makeEdit(this, "");
   var out = makeEdit(this, "");
   var backend = makeEdit(this, "cuda");
   var memoryMode = makeEdit(this, "resident");
   var localNormalization = makeEdit(this, "off");
   var integrationWeighting = makeEdit(this, "none");
   var integrationRejection = makeEdit(this, "winsorized_sigma");
   var residentRegistration = makeEdit(this, "similarity_cuda_triangle");
   var residentWarpInterpolation = makeEdit(this, "lanczos3");

   var grid = new Sizer();
   grid.margin = 8;
   grid.spacing = 6;

   function addRow(dialog, labelText, control) {
      var row = new HorizontalSizer();
      row.spacing = 6;
      row.add(makeLabel(dialog, labelText));
      row.add(control, 100);
      grid.add(row);
   }

   addRow(this, "gpwbpp executable:", executable);
   addRow(this, "input root:", root);
   addRow(this, "output run directory:", out);
   addRow(this, "backend:", backend);
   addRow(this, "memory mode:", memoryMode);
   addRow(this, "local normalization:", localNormalization);
   addRow(this, "integration weighting:", integrationWeighting);
   addRow(this, "integration rejection:", integrationRejection);
   addRow(this, "resident registration:", residentRegistration);
   addRow(this, "resident warp:", residentWarpInterpolation);

   var note = new Label(this);
   note.text = "Clean-room launcher: calls external GPWBPP only; input directories are read-only.";
   note.textAlignment = TextAlign_Left | TextAlign_VertCenter;
   grid.add(note);

   var buttons = new HorizontalSizer();
   buttons.spacing = 6;
   buttons.addStretch();

   var writeButton = new PushButton(this);
   writeButton.text = "Write command file";
   buttons.add(writeButton);

   var runButton = new PushButton(this);
   runButton.text = "Run";
   buttons.add(runButton);

   var closeButton = new PushButton(this);
   closeButton.text = "Close";
   buttons.add(closeButton);
   grid.add(buttons);

   function settings() {
      return {
         executable: executable.text,
         root: root.text,
         out: out.text,
         backend: backend.text,
         memoryMode: memoryMode.text,
         localNormalization: localNormalization.text,
         integrationWeighting: integrationWeighting.text,
         integrationRejection: integrationRejection.text,
         residentRegistration: residentRegistration.text,
         residentWarpInterpolation: residentWarpInterpolation.text
      };
   }

   writeButton.onClick = function() {
      writeCommandFile(settings());
   };

   runButton.onClick = function() {
      runExternal(settings());
   };

   closeButton.onClick = function() {
      this.dialog.cancel();
   };

   this.sizer = grid;
   this.adjustToContents();
}

GPWBPPDialog.prototype = new Dialog;

var dialog = new GPWBPPDialog();
dialog.execute();
